apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-cluster-deployment
  labels:
    app: odoo-cluster-deployment
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-cluster-deployment
  template:
    metadata:
      labels:
        app: odoo-cluster-deployment
        tier: frontend
    spec:
      containers:
        - image: checkraiser/webshop_frontend
          name: odoo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: odoo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo-cluster-svc
  name: odoo-cluster-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: odoo-cluster-deployment
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: odoo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-connections: '10'
    nginx.ingress.kubernetes.io/limit-rpm: '60'
    nginx.ingress.kubernetes.io/service-upstream: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - checkraiser.tinmua.vn
      secretName: odoo-tls
  rules:
  - host: checkraiser.tinmua.vn
    http:
      paths:
      - backend:
          serviceName: odoo-cluster-svc
          servicePort: 80  