pipeline:
  publish:
    image: plugins/docker
    dockerfile: ./backend/Dockerfile
    context: ./backend
    repo: checkraiser/webshop_backend
    tags: [latest, v1]
    secrets: [ docker_username, docker_password ]
  